# Generated by Django 3.2.9 on 2021-11-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='ooption_two',
            new_name='option_two',
        ),
    ]
